name: deploy to GKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout REPOSITORY
      uses: actions/checkout@v4
    - name: Autheticate with google cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin"
    - name: Authenticate to GKE cluster
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: forgithubaction
        location: us-central1

    - name: Configure Docker for Artifact REGISTRY
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    - name: Build and push docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/se-poc-347619/githubactionrepo/twotier:latest .
        docker push us-central1-docker.pkg.dev/se-poc-347619/githubactionrepo/twotier:latest

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials forgithubaction --region us-central1 --project se-poc-347619
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
    - name: Deploy to GKE
      run: |
        kubectl apply -f mysql.yml
        kubectl apply -f two-tier-app.yml
